before:
  hooks:
    - go mod download
builds:
  -
    binary: myof-client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
    ldflags:
      - -X github.com/myopenfactory/client/cmd.Version={{.Version}} -X github.com/myopenfactory/client/cmd.Date={{.Date}} -X github.com/myopenfactory/client/cmd.Commit={{.Commit}}
archive:
  name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
      - myof-client
    dockerfile: Dockerfile
    image_templates:
      - "myopenfactory.azurecr.io/client:alpine-latest"
      - "myopenfactory.azurecr.io/client:alpine-{{ .Version }}"
    extra_files:
      - myOpenFactoryCA.crt
sign:
  signature: "${artifact}.sig"
  cmd: openssl
  args: ["dgst", "-sha256", "-sign", "myOpenFactory_Development.pem", "-out", "${signature}", "${artifact}"]
  artifacts: all
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
