name: CI

on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - run: |
        go test ./...
    - name: Build
      shell: bash
      run: |
        BUILD_COMMIT=`git rev-parse --short HEAD`
        BUILD_DATE=`date -Iseconds`
        CGO_ENABLED=0 go build -o myof-client -ldflags "-X github.com/myopenfactory/client/pkg/version.Date=${BUILD_DATE} -X github.com/myopenfactory/client/pkg/version.Commit=${BUILD_COMMIT}"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Fetch auth and sign informations
      env:
        SIGN_CERTIFICATE: ${{ secrets.SIGN_CERTIFICATE }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "$SIGN_CERTIFICATE" > myOpenFactory_Development.pem
        docker login -u "myofci" -p "${DOCKERHUB_TOKEN}" 
    - uses: crazy-max/ghaction-goreleaser@master
      with:
        args: --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
