name: CI

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      -
        name: Prepare sign certificate
        run: echo -n ${SIGN_CERTIFICATE} | base64 --decode > $HOME/key.asc
        env:
          SIGN_CERTIFICATE: ${{ secrets.SIGN_CERTIFICATE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
